### ISSUE TITLE
Ensure PR approval is from the required approvers.

### ISSUE THREAD

**Issue by sqin2019** [abcxyz/access-on-demand#57]
currently: https://github.com/abcxyz/access-on-demand/blob/main/.github/workflows/handle.yml#L48
maybe better to use reviewDecision in graphql: https://github.com/orgs/community/discussions/24702

**Comment by yolocs** [comment]
We should try this out.

**Comment by sqin2019** [comment]
> We should try this out.

I added in the CLIRequest cleanup/undo workflow, https://github.com/abcxyz/access-on-demand/blob/main/.github/workflows/cleanup.yml#L47, once we updated the aod-template to use the newest commit, we can test it out there.
