### ISSUE TITLE
fix aod cli commands

### ISSUE THREAD

**Issue by sqin2019** [abcxyz/access-on-demand#58]
follow up of https://github.com/abcxyz/access-on-demand/pull/52#discussion_r1242950067

Attempted to make cleanup a flag as below, but it could cause confusions as mentioned by Xiyue [here](https://github.com/abcxyz/access-on-demand/pull/55#issuecomment-1612076098)
```aod cli handle -path <path> -cleanup```

Think of a better alternative.

**Comment by sqin2019** [comment]
How about use a CommandType enum? @capri-xiyue @sethvargo 
```
						"do": func() cli.Command {
							return &CLIHandleCommand{CommandType: Do}
						},
						"cleanup": func() cli.Command {
							return &CLIHandleCommand{CommandType: Cleanup}
						},
```

**Comment by sethvargo** [comment]
My suggestion would be to have two commands: `DoCommand` and `CleanupCommand`. What are you trying to achieve by using the same command struct for different entrypoints?

**Comment by yolocs** [comment]
We can do an easy refactoring to pull out the common logic to run commands. And have two commands use the common logic

**Comment by sqin2019** [comment]
fixed.
