### ISSUE TITLE
Use "gcloud" as the subcommand to run gcloud commands

### ISSUE THREAD

**Issue by yolocs** [abcxyz/access-on-demand#60]
https://github.com/abcxyz/access-on-demand/blob/main/pkg/cli/root.go#L45

`cli` as the subcommand name is confusing

**Comment by sqin2019** [comment]
> https://github.com/abcxyz/access-on-demand/blob/main/pkg/cli/root.go#L45
> 
> `cli` as the subcommand name is confusing

Wouldn't we want to extend it to support other clouds too like aws?
