### ISSUE TITLE
Have better output

### ISSUE THREAD

**Issue by yolocs** [abcxyz/access-on-demand#79]
`-verbose` flag will have the commands to output what actions it has taken. E.g.

```
Applied the following IAM bindings:

[The request]
```

```
Executed the following commands:

gcloud xxx
```

Having this standard output will make posting comments easier - it no longer needs to read the request file.

And maybe as a separate issue to have a `-debug` flag to print out more details. For IAM, it will be the whole IAM policies set. For gcloud, it will print out the gcloud output.

**Comment by sqin2019** [comment]
note: -[debug](https://github.com/abcxyz/access-on-demand/blob/main/pkg/cli/tool_base.go#L40) flag for gcloud/tool is already supported.

**Comment by sethvargo** [comment]
I'd prefer if we use log-levels (e.g. -log-level=debug) instead of `-debug`.

**Comment by yolocs** [comment]
> I'd prefer if we use log-levels (e.g. -log-level=debug) instead of `-debug`.

I think we named it "debug" because we feel it represents debug mode (vs. debug logging). For IAM request, we'd like to output the whole IAM policies (which might include existing bindings). For gcloud request, we'd like to output the gcloud output. In my mental model, they don't fit into the logging scope. Any suggestion on the naming?

**Comment by sethvargo** [comment]
What do we expect to happen in `-debug`? It feels like we want to log the gcloud request and log the IAM policies; that feels like logging :)

**Comment by yolocs** [comment]
> What do we expect to happen in `-debug`? It feels like we want to log the gcloud request and log the IAM policies; that feels like logging :)

I can accept that :) but currently in debug mode we write to `c.Stdout()`. We should switch to using logger if we use log level. cc @sqin2019

**Comment by sqin2019** [comment]
I feel like it is not logging, does `-output` make sense?

**Comment by yolocs** [comment]
> I feel like it is not logging, or maybe it is just a small part of it, does `-output` make sense?

That's even more confusing. We output even without this flag (e.g. "Successfully applied ...").

Maybe we can consolidate this?

- We always output what's in https://github.com/abcxyz/access-on-demand/pull/84
- Use `-verbose` flag to control whether we output the whole IAM policies and gcloud output.
